"""shifts_and_user_columns

Revision ID: 1f38074872ac
Revises: 274f344764e1
Create Date: 2026-04-17 09:13:48.577448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f38074872ac'
down_revision: Union[str, None] = '274f344764e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lone_worker_shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lone_worker_shifts_user_id'), 'lone_worker_shifts', ['user_id'], unique=False)
    op.add_column('users', sa.Column('shift_duration_hours', sa.Integer(), nullable=True))
    # server_default ensures existing rows get a value so the NOT NULL
    # constraint can apply; the default is kept server-side afterward too.
    op.add_column('users', sa.Column(
        'can_answer_calls', sa.Boolean(), nullable=False,
        server_default=sa.false(),
    ))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_lone_worker',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_lone_worker',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'can_answer_calls')
    op.drop_column('users', 'shift_duration_hours')
    op.drop_index(op.f('ix_lone_worker_shifts_user_id'), table_name='lone_worker_shifts')
    op.drop_table('lone_worker_shifts')
    # ### end Alembic commands ###
