#!/usr/bin/env bash
# =============================================================================
# PTT Server Installer
# One-command install for Ubuntu 25.04 VPS
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/harrowiersma/PTT/main/scripts/install.sh | bash
#
# Or clone and run:
#   git clone https://github.com/harrowiersma/PTT.git && cd PTT && bash scripts/install.sh
# =============================================================================
set -euo pipefail

PTT_DIR="${PTT_DIR:-/opt/ptt}"
REPO="https://github.com/harrowiersma/PTT.git"

echo "================================================"
echo "  PTT Server Installer"
echo "  Admin:  https://ptt.harro.ch"
echo "  Voice:  https://voice.harro.ch"
echo "================================================"
echo ""

# --- Check root ---
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root (or with sudo)."
    echo "  sudo bash scripts/install.sh"
    exit 1
fi

# --- Check Ubuntu ---
if ! grep -qi "ubuntu" /etc/os-release 2>/dev/null; then
    echo "WARNING: This script is designed for Ubuntu. Proceeding anyway..."
fi

# --- Install Docker if not present ---
if ! command -v docker &>/dev/null; then
    echo "[1/6] Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo "  Docker installed."
else
    echo "[1/6] Docker already installed."
fi

# --- Install Docker Compose plugin if not present ---
if ! docker compose version &>/dev/null; then
    echo "[2/6] Installing Docker Compose plugin..."
    apt-get update -qq
    apt-get install -y -qq docker-compose-plugin
    echo "  Docker Compose installed."
else
    echo "[2/6] Docker Compose already installed."
fi

# --- Install git if not present ---
if ! command -v git &>/dev/null; then
    apt-get update -qq
    apt-get install -y -qq git
fi

# --- Clone or update repo ---
if [ -d "$PTT_DIR/.git" ]; then
    echo "[3/6] Updating existing installation at $PTT_DIR..."
    cd "$PTT_DIR"
    git pull --ff-only
else
    echo "[3/6] Cloning PTT server to $PTT_DIR..."
    git clone "$REPO" "$PTT_DIR"
    cd "$PTT_DIR"
fi

# --- Generate .env if not exists ---
if [ ! -f "$PTT_DIR/.env" ]; then
    echo "[4/6] Generating configuration..."
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || openssl rand -base64 32)

    cat > "$PTT_DIR/.env" <<EOF
# PTT Admin Service Configuration
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

PTT_ADMIN_USERNAME=admin
PTT_ADMIN_PASSWORD=$(openssl rand -base64 12 | tr -d '/+=' | head -c 16)
PTT_SECRET_KEY=${SECRET_KEY}

PTT_DATABASE_URL=postgresql+asyncpg://ptt:ptt@postgres:5432/ptt
PTT_DATABASE_URL_SYNC=postgresql+psycopg2://ptt:ptt@postgres:5432/ptt

PTT_MURMUR_ICE_HOST=murmur
PTT_MURMUR_ICE_PORT=6502
PTT_MURMUR_ICE_SECRET=

PTT_PUBLIC_HOST=voice.harro.ch
PTT_PUBLIC_PORT=443
EOF

    ADMIN_PASS=$(grep PTT_ADMIN_PASSWORD "$PTT_DIR/.env" | cut -d= -f2)
    echo "  Config generated. Admin password: $ADMIN_PASS"
    echo "  (Save this password! It's in $PTT_DIR/.env)"
else
    echo "[4/6] Config already exists at $PTT_DIR/.env, keeping it."
fi

# --- Configure firewall ---
echo "[5/6] Configuring firewall..."
if command -v ufw &>/dev/null; then
    ufw allow 443/tcp   >/dev/null 2>&1 || true
    ufw allow 80/tcp    >/dev/null 2>&1 || true
    ufw allow 64738/tcp >/dev/null 2>&1 || true
    ufw allow 64738/udp >/dev/null 2>&1 || true
    echo "  Firewall rules added (443, 80, 64738)."
else
    echo "  ufw not found, skipping firewall config."
fi

# --- Start services ---
echo "[6/6] Starting PTT server..."
cd "$PTT_DIR"
docker compose pull
docker compose build --quiet
docker compose up -d

echo ""
echo "================================================"
echo "  PTT Server is running!"
echo "================================================"
echo ""
echo "  Admin panel:  http://ptt.harro.ch  (port 80)"
echo "  Voice server: voice.harro.ch:64738 (Mumble)"
echo ""
echo "  Admin login:"
ADMIN_USER=$(grep PTT_ADMIN_USERNAME "$PTT_DIR/.env" | cut -d= -f2)
ADMIN_PASS=$(grep PTT_ADMIN_PASSWORD "$PTT_DIR/.env" | cut -d= -f2)
echo "    Username: $ADMIN_USER"
echo "    Password: $ADMIN_PASS"
echo ""
echo "  Config file: $PTT_DIR/.env"
echo ""
echo "  Next steps:"
echo "    1. Set up DNS: point ptt.harro.ch and voice.harro.ch to this server"
echo "    2. Set up TLS: sudo $PTT_DIR/scripts/setup-tls.sh"
echo "    3. Create users in the admin panel"
echo "    4. Sideload HamMumble on P50 devices"
echo ""
echo "  Manage:"
echo "    cd $PTT_DIR && docker compose logs -f    # view logs"
echo "    cd $PTT_DIR && docker compose restart     # restart"
echo "    cd $PTT_DIR && docker compose down        # stop"
echo "================================================"
