#!/usr/bin/env bash
# =============================================================================
# PTT Server Installer
# One-command install for Ubuntu 25.04 VPS
#
# Installs Docker, clones the repo, generates config, obtains Let's Encrypt
# TLS certificates for ptt.harro.ch and voice.harro.ch, and starts everything.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/harrowiersma/PTT/main/scripts/install.sh | sudo bash
#
# Prerequisites:
#   - Ubuntu VPS with root access
#   - DNS A records already pointing to this server:
#       ptt.harro.ch   -> <this server IP>
#       voice.harro.ch -> <this server IP>
# =============================================================================
set -euo pipefail

PTT_DIR="${PTT_DIR:-/opt/ptt}"
REPO="https://github.com/harrowiersma/PTT.git"
LE_EMAIL="harro@wiersma.info"
DOMAIN_ADMIN="ptt.harro.ch"
DOMAIN_VOICE="voice.harro.ch"

echo "================================================"
echo "  PTT Server Installer"
echo "  Admin:  https://$DOMAIN_ADMIN"
echo "  Voice:  $DOMAIN_VOICE:443"
echo "================================================"
echo ""

# --- Check root ---
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root (or with sudo)."
    echo "  curl -fsSL https://raw.githubusercontent.com/harrowiersma/PTT/main/scripts/install.sh | sudo bash"
    exit 1
fi

# --- Check Ubuntu ---
if ! grep -qi "ubuntu" /etc/os-release 2>/dev/null; then
    echo "WARNING: This script is designed for Ubuntu. Proceeding anyway..."
fi

# --- Step 1: Install Docker ---
if ! command -v docker &>/dev/null; then
    echo "[1/8] Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo "       Done."
else
    echo "[1/8] Docker already installed."
fi

# --- Step 2: Install Docker Compose plugin ---
if ! docker compose version &>/dev/null; then
    echo "[2/8] Installing Docker Compose plugin..."
    apt-get update -qq
    apt-get install -y -qq docker-compose-plugin
    echo "       Done."
else
    echo "[2/8] Docker Compose already installed."
fi

# --- Step 3: Install certbot and git ---
echo "[3/8] Installing certbot and git..."
apt-get update -qq
apt-get install -y -qq certbot git
echo "       Done."

# --- Step 4: Clone or update repo ---
if [ -d "$PTT_DIR/.git" ]; then
    echo "[4/8] Updating existing installation at $PTT_DIR..."
    cd "$PTT_DIR"
    git pull --ff-only
else
    echo "[4/8] Cloning PTT server to $PTT_DIR..."
    git clone "$REPO" "$PTT_DIR"
    cd "$PTT_DIR"
fi

# --- Step 5: Generate .env ---
if [ ! -f "$PTT_DIR/.env" ]; then
    echo "[5/8] Generating configuration..."
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || openssl rand -hex 32)
    ADMIN_PASS=$(openssl rand -base64 12 | tr -d '/+=' | head -c 16)
    DB_PASS=$(openssl rand -hex 16)

    cat > "$PTT_DIR/.env" <<EOF
# PTT Admin Service Configuration
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

PTT_ADMIN_USERNAME=admin
PTT_ADMIN_PASSWORD=${ADMIN_PASS}
PTT_SECRET_KEY=${SECRET_KEY}

PTT_DATABASE_URL=postgresql+asyncpg://ptt:${DB_PASS}@postgres:5432/ptt
PTT_DATABASE_URL_SYNC=postgresql+psycopg2://ptt:${DB_PASS}@postgres:5432/ptt

PTT_MURMUR_ICE_HOST=murmur
PTT_MURMUR_ICE_PORT=6502
PTT_MURMUR_ICE_SECRET=

PTT_PUBLIC_HOST=${DOMAIN_VOICE}
PTT_PUBLIC_PORT=443

# PostgreSQL (used by docker-compose.yml)
POSTGRES_PASSWORD=${DB_PASS}
EOF

    echo ""
    echo "  ┌────────────────────────────────────────────┐"
    echo "  │  SAVE THESE CREDENTIALS                    │"
    echo "  │                                            │"
    echo "  │  Username: admin                           │"
    echo "  │  Password: ${ADMIN_PASS}              │"
    echo "  │                                            │"
    echo "  │  Stored in: $PTT_DIR/.env     │"
    echo "  │  Retrieve later:                           │"
    echo "  │    grep PTT_ADMIN_PASSWORD $PTT_DIR/.env   │"
    echo "  └────────────────────────────────────────────┘"
    echo ""
else
    echo "[5/8] Config already exists at $PTT_DIR/.env, keeping it."
    ADMIN_PASS=$(grep PTT_ADMIN_PASSWORD "$PTT_DIR/.env" | cut -d= -f2)
fi

# --- Step 6: Configure firewall ---
echo "[6/8] Configuring firewall..."
if command -v ufw &>/dev/null; then
    ufw allow 443/tcp   >/dev/null 2>&1 || true
    ufw allow 80/tcp    >/dev/null 2>&1 || true
    ufw allow 64738/tcp >/dev/null 2>&1 || true
    ufw allow 64738/udp >/dev/null 2>&1 || true
    echo "       Firewall rules added (443, 80, 64738)."
else
    echo "       ufw not found, skipping firewall config."
fi

# --- Step 7: Obtain Let's Encrypt TLS certificates ---
echo "[7/8] Obtaining TLS certificates from Let's Encrypt..."
echo "       (DNS must already point $DOMAIN_ADMIN and $DOMAIN_VOICE to this server)"
echo ""

CERTS_OK=true

# Check if certs already exist
if [ -d "/etc/letsencrypt/live/$DOMAIN_ADMIN" ] && [ -d "/etc/letsencrypt/live/$DOMAIN_VOICE" ]; then
    echo "       Certificates already exist, skipping."
else
    # Make sure ports 80/443 are free for certbot standalone
    docker compose down 2>/dev/null || true
    systemctl stop nginx 2>/dev/null || true
    systemctl stop apache2 2>/dev/null || true

    # Get cert for admin domain
    if [ ! -d "/etc/letsencrypt/live/$DOMAIN_ADMIN" ]; then
        echo "       Requesting certificate for $DOMAIN_ADMIN..."
        if certbot certonly --standalone -d "$DOMAIN_ADMIN" \
            --non-interactive --agree-tos --email "$LE_EMAIL" 2>&1; then
            echo "       Certificate obtained for $DOMAIN_ADMIN"
        else
            echo "       WARNING: Failed to get certificate for $DOMAIN_ADMIN"
            echo "       Make sure DNS A record points to this server."
            echo "       You can retry later: certbot certonly --standalone -d $DOMAIN_ADMIN --email $LE_EMAIL"
            CERTS_OK=false
        fi
    fi

    # Get cert for voice domain
    if [ ! -d "/etc/letsencrypt/live/$DOMAIN_VOICE" ]; then
        echo "       Requesting certificate for $DOMAIN_VOICE..."
        if certbot certonly --standalone -d "$DOMAIN_VOICE" \
            --non-interactive --agree-tos --email "$LE_EMAIL" 2>&1; then
            echo "       Certificate obtained for $DOMAIN_VOICE"
        else
            echo "       WARNING: Failed to get certificate for $DOMAIN_VOICE"
            echo "       Make sure DNS A record points to this server."
            echo "       You can retry later: certbot certonly --standalone -d $DOMAIN_VOICE --email $LE_EMAIL"
            CERTS_OK=false
        fi
    fi
fi

# --- Enable SSL config if certs were obtained ---
if [ "$CERTS_OK" = true ]; then
    # Copy the SSL config so Nginx loads it
    cp "$PTT_DIR/nginx-ssl.conf" "$PTT_DIR/nginx-ssl-active.conf"
else
    # Create empty file so Docker mount doesn't fail
    echo "# TLS not configured yet. Run certbot and restart." > "$PTT_DIR/nginx-ssl-active.conf"
fi

# --- Step 8: Start services ---
echo "[8/8] Starting PTT server..."
cd "$PTT_DIR"
docker compose pull
docker compose build --quiet
docker compose up -d

# Wait a moment for services to start
sleep 3

# Quick health check
if docker compose ps --format "{{.Status}}" | grep -q "Up"; then
    echo "       All containers running."
else
    echo "       WARNING: Some containers may not be running. Check with:"
    echo "         cd $PTT_DIR && docker compose ps"
fi

echo ""
echo "================================================"
echo "  PTT Server is running!"
echo "================================================"
echo ""
if [ "$CERTS_OK" = true ]; then
    echo "  Admin panel:  https://$DOMAIN_ADMIN"
    echo "  Voice server: $DOMAIN_VOICE:443 (Mumble TLS)"
else
    echo "  Admin panel:  http://$DOMAIN_ADMIN  (TLS failed, see warnings above)"
    echo "  Voice server: $DOMAIN_VOICE:64738   (Mumble, fallback port)"
fi
echo ""
echo "  ┌────────────────────────────────────────────┐"
echo "  │  Admin login:                              │"
echo "  │    Username: admin                         │"
echo "  │    Password: ${ADMIN_PASS}            │"
echo "  └────────────────────────────────────────────┘"
echo ""
echo "  Config:    $PTT_DIR/.env"
echo "  Certs:     /etc/letsencrypt/live/$DOMAIN_ADMIN/"
echo "             /etc/letsencrypt/live/$DOMAIN_VOICE/"
echo ""
echo "  Next steps:"
echo "    1. Log into https://$DOMAIN_ADMIN"
echo "    2. Create channels (e.g., Warehouse, Office, Security)"
echo "    3. Create users with passwords"
echo "    4. Click QR on each user to get enrollment code"
echo "    5. Sideload HamMumble on P50, scan QR code"
echo ""
echo "  Manage:"
echo "    cd $PTT_DIR && docker compose logs -f    # view logs"
echo "    cd $PTT_DIR && docker compose restart     # restart"
echo "    cd $PTT_DIR && docker compose down        # stop"
echo ""
echo "  TLS auto-renewal is handled by certbot's systemd timer."

# Set up daily backup cron
if ! crontab -l 2>/dev/null | grep -q "backup.sh"; then
    (crontab -l 2>/dev/null; echo "0 3 * * * $PTT_DIR/scripts/backup.sh >> /var/log/ptt-backup.log 2>&1") | crontab -
    echo "  Daily backup cron installed (3:00 AM)"
fi

# Set up systemd service for auto-start on reboot
cat > /etc/systemd/system/ptt.service <<SVCEOF
[Unit]
Description=PTT Server (Docker Compose)
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$PTT_DIR
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
SVCEOF
systemctl daemon-reload
systemctl enable ptt.service 2>/dev/null || true
echo "  Verify: certbot renew --dry-run"
echo "================================================"
